// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/weaviate.proto

package io.weaviate.client6.v1.internal.grpc.protocol;

public final class WeaviateProto {
  private WeaviateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021v1/weaviate.proto\022\013weaviate.v1\032\022v1/agg" +
      "regate.proto\032\016v1/batch.proto\032\025v1/batch_d" +
      "elete.proto\032\023v1/search_get.proto\032\020v1/ten" +
      "ants.proto2\274\004\n\010Weaviate\022@\n\006Search\022\032.weav" +
      "iate.v1.SearchRequest\032\030.weaviate.v1.Sear" +
      "chReply\"\000\022R\n\014BatchObjects\022 .weaviate.v1." +
      "BatchObjectsRequest\032\036.weaviate.v1.BatchO" +
      "bjectsReply\"\000\022[\n\017BatchReferences\022#.weavi" +
      "ate.v1.BatchReferencesRequest\032!.weaviate" +
      ".v1.BatchReferencesReply\"\000\022O\n\013BatchDelet" +
      "e\022\037.weaviate.v1.BatchDeleteRequest\032\035.wea" +
      "viate.v1.BatchDeleteReply\"\000\022L\n\nTenantsGe" +
      "t\022\036.weaviate.v1.TenantsGetRequest\032\034.weav" +
      "iate.v1.TenantsGetReply\"\000\022I\n\tAggregate\022\035" +
      ".weaviate.v1.AggregateRequest\032\033.weaviate" +
      ".v1.AggregateReply\"\000\022S\n\013BatchStream\022\037.we" +
      "aviate.v1.BatchStreamRequest\032\035.weaviate." +
      "v1.BatchStreamReply\"\000(\0010\001B>\n-io.weaviate" +
      ".client6.v1.internal.grpc.protocolB\rWeav" +
      "iateProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoAggregate.getDescriptor(),
          io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoBatch.getDescriptor(),
          io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoBatchDelete.getDescriptor(),
          io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoSearchGet.getDescriptor(),
          io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoTenants.getDescriptor(),
        });
    io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoAggregate.getDescriptor();
    io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoBatch.getDescriptor();
    io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoBatchDelete.getDescriptor();
    io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoSearchGet.getDescriptor();
    io.weaviate.client6.v1.internal.grpc.protocol.WeaviateProtoTenants.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
