package io.weaviate.client6.v1.api.collections.batch;

interface State {
  /**
   * canSend returns a boolean indicating if sending
   * an "insert" message is allowed in this state.
   */
  boolean canSend();

  /**
   * canPrepareNext returns a boolean indicating if accepting
   * more items into the batch is allowed in this state.
   */
  boolean canPrepareNext();

  /**
   * Lifecycle hook that's called after the state is set.
   *
   * <p>
   * <br>
   * This hook MUST be called exactly once.
   * <br>
   * The next state MUST NOT be set until onEnter returns.
   *
   * @param prev Previous state or null.
   */
  void onEnter(State prev);

  /**
   * onEvent handles incoming events; these can be generated by the server
   * or by a different part of the program -- the {@link State} MUST NOT
   * make any assumptions about the event's origin.
   *
   * <p>
   * How the event is handled is up to the concrete implementation.
   * It may modify {@link BatchContext} internal state, via one of it's
   * package-private methods, including transitioning the context to a
   * different state via {@link BatchContext#setState(State)}, or start
   * a separate process, e.g. the OOM timer.
   */
  void onEvent(Event event);
}
