package io.weaviate.client6.v1.api.collections.batch;

interface State {
  /**
   * canSend returns a boolean indicating if sending
   * an "insert" message is allowed in this state.
   */
  boolean canSend();

  /**
   * canTake returns a boolean indicating if accepting
   * more items into the batch is allowed in this state.
   */
  boolean canTake();

  /**
   * onEvent handles incoming events; these can be generated by the server
   * or by a different part of the program -- the {@link State} MUST NOT
   * make any assumptions about the event's origin.
   *
   * <p>
   * How the event is handled is up to the concrete implementation.
   * It may modify {@link BatchContext} internal state, via one of it's
   * package-private methods, including transitioning the context to a
   * different state via {@link BatchContext#setState(State)}, or start
   * a separate process, e.g. the OOM timer.
   */
  void onEvent(Event event) throws InterruptedException;
}
