package io.weaviate.client6.v1.api.collections.batch;

interface State {
  /**
   * canSend returns a boolean indicating if sending
   * an "insert" message is allowed in this state.
   */
  boolean canSend();

  /**
   * onEvent handles incoming events; these can be generated by the server
   * or by a different part of the program -- the {@link State} MUST NOT
   * make any assumptions about the event's origin.
   *
   * <p>
   * How the event is handled is up to the concrete implementation.
   * It may modify {@link BatchContext} internal state, via one of it's
   * package-private methods, including transitioning the context to a
   * different state via {@link BatchContext#setState(State)}, or start
   * a separate process, e.g. the OOM timer.
   */
  void onEvent(Event event) throws InterruptedException;

  abstract class BaseState implements State {
    @Override
    public void onEvent(Event event) {
      if (event instanceof Event.Acks acks) {

      } else if (event instanceof Event.Results results) {

      } else if (event instanceof Event.Backoff backoff) {

      } else if (event == Event.OOM) {

      } else if (event == Event.SHUTTING_DOWN) {

      } else {
        throw new IllegalStateException("cannot handle " + event.getClass());
      }
    }
  }
}
