// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v0/weaviate.proto

package io.weaviate.client6.grpc.protocol.v0;

public final class WeaviateProto {
  private WeaviateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021v0/weaviate.proto\022\014weaviategrpc\032\016v0/ba" +
      "tch.proto\032\023v0/search_get.proto2\244\001\n\010Weavi" +
      "ate\022B\n\006Search\022\033.weaviategrpc.SearchReque" +
      "st\032\031.weaviategrpc.SearchReply\"\000\022T\n\014Batch" +
      "Objects\022!.weaviategrpc.BatchObjectsReque" +
      "st\032\037.weaviategrpc.BatchObjectsReply\"\000Bk\n" +
      "$io.weaviate.client6.grpc.protocol.v0B\rW" +
      "eaviateProtoZ4github.com/weaviate/weavia" +
      "te/grpc/generated;protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.weaviate.client6.grpc.protocol.v0.WeaviateProtoBatch.getDescriptor(),
          io.weaviate.client6.grpc.protocol.v0.WeaviateProtoSearchGet.getDescriptor(),
        });
    io.weaviate.client6.grpc.protocol.v0.WeaviateProtoBatch.getDescriptor();
    io.weaviate.client6.grpc.protocol.v0.WeaviateProtoSearchGet.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
