// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/weaviate.proto

package io.weaviate.client.grpc.protocol.v1;

public final class WeaviateProto {
  private WeaviateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021v1/weaviate.proto\022\013weaviate.v1\032\016v1/bat" +
      "ch.proto\032\023v1/search_get.proto2\240\001\n\010Weavia" +
      "te\022@\n\006Search\022\032.weaviate.v1.SearchRequest" +
      "\032\030.weaviate.v1.SearchReply\"\000\022R\n\014BatchObj" +
      "ects\022 .weaviate.v1.BatchObjectsRequest\032\036" +
      ".weaviate.v1.BatchObjectsReply\"\000Bj\n#io.w" +
      "eaviate.client.grpc.protocol.v1B\rWeaviat" +
      "eProtoZ4github.com/weaviate/weaviate/grp" +
      "c/generated;protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.weaviate.client.grpc.protocol.v1.WeaviateProtoBatch.getDescriptor(),
          io.weaviate.client.grpc.protocol.v1.WeaviateProtoSearchGet.getDescriptor(),
        });
    io.weaviate.client.grpc.protocol.v1.WeaviateProtoBatch.getDescriptor();
    io.weaviate.client.grpc.protocol.v1.WeaviateProtoSearchGet.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
