// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/weaviate.proto

package io.weaviate.client.grpc.protocol.v1;

public final class WeaviateProto {
  private WeaviateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021v1/weaviate.proto\022\013weaviate.v1\032\016v1/bat" +
      "ch.proto\032\025v1/batch_delete.proto\032\023v1/sear" +
      "ch_get.proto2\361\001\n\010Weaviate\022@\n\006Search\022\032.we" +
      "aviate.v1.SearchRequest\032\030.weaviate.v1.Se" +
      "archReply\"\000\022R\n\014BatchObjects\022 .weaviate.v" +
      "1.BatchObjectsRequest\032\036.weaviate.v1.Batc" +
      "hObjectsReply\"\000\022O\n\013BatchDelete\022\037.weaviat" +
      "e.v1.BatchDeleteRequest\032\035.weaviate.v1.Ba" +
      "tchDeleteReply\"\000Bj\n#io.weaviate.client.g" +
      "rpc.protocol.v1B\rWeaviateProtoZ4github.c" +
      "om/weaviate/weaviate/grpc/generated;prot" +
      "ocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.weaviate.client.grpc.protocol.v1.WeaviateProtoBatch.getDescriptor(),
          io.weaviate.client.grpc.protocol.v1.WeaviateProtoBatchDelete.getDescriptor(),
          io.weaviate.client.grpc.protocol.v1.WeaviateProtoSearchGet.getDescriptor(),
        });
    io.weaviate.client.grpc.protocol.v1.WeaviateProtoBatch.getDescriptor();
    io.weaviate.client.grpc.protocol.v1.WeaviateProtoBatchDelete.getDescriptor();
    io.weaviate.client.grpc.protocol.v1.WeaviateProtoSearchGet.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
